/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StationRouteImport } from './routes/station'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as WireRouteImport } from './routes/wire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StationRoute = StationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const WireRoute = WireRouteImport.update({
  id: '/wire',
  path: '/wire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conductor': typeof ConductorRoute
  '/ledger': typeof LedgerRoute
  '/people': typeof PeopleRoute
  '/reports': typeof ReportsRoute
  '/station': typeof StationRoute
  '/systems': typeof SystemsRoute
  '/wire': typeof WireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conductor': typeof ConductorRoute
  '/ledger': typeof LedgerRoute
  '/people': typeof PeopleRoute
  '/reports': typeof ReportsRoute
  '/station': typeof StationRoute
  '/systems': typeof SystemsRoute
  '/wire': typeof WireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conductor': typeof ConductorRoute
  '/ledger': typeof LedgerRoute
  '/people': typeof PeopleRoute
  '/reports': typeof ReportsRoute
  '/station': typeof StationRoute
  '/systems': typeof SystemsRoute
  '/wire': typeof WireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conductor'
    | '/ledger'
    | '/people'
    | '/reports'
    | '/station'
    | '/systems'
    | '/wire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conductor'
    | '/ledger'
    | '/people'
    | '/reports'
    | '/station'
    | '/systems'
    | '/wire'
  id:
    | '__root__'
    | '/'
    | '/conductor'
    | '/ledger'
    | '/people'
    | '/reports'
    | '/station'
    | '/systems'
    | '/wire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConductorRoute: typeof ConductorRoute
  LedgerRoute: typeof LedgerRoute
  PeopleRoute: typeof PeopleRoute
  ReportsRoute: typeof ReportsRoute
  StationRoute: typeof StationRoute
  SystemsRoute: typeof SystemsRoute
  WireRoute: typeof WireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station': {
      id: '/station'
      path: '/station'
      fullPath: '/station'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wire': {
      id: '/wire'
      path: '/wire'
      fullPath: '/wire'
      preLoaderRoute: typeof WireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConductorRoute: ConductorRoute,
  LedgerRoute: LedgerRoute,
  PeopleRoute: PeopleRoute,
  ReportsRoute: ReportsRoute,
  StationRoute: StationRoute,
  SystemsRoute: SystemsRoute,
  WireRoute: WireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
